[#159] Improvement/issue 159 validate library version
singnet/das-query-engine pull request #163
Opened 2024-03-01 15:08 UTC by marcocapozzoli

Resolves #159

2024-03-01 17:03 UTC, andre-senna requested changes

2024-03-01 17:03 UTC, andre-senna commented on hyperon_das/query_engines.py
> +                    'The version of the package you provided does not match the version currently running on the server.'
The error message should provide both, the given version and the required one.

2024-03-04 19:47 UTC, andre-senna approved these changes

2024-03-04 19:49 UTC, andre-senna commented
@levisingularity  Please review this PR as well to make sure client/handle communication is OK

2024-03-11 20:00 UTC, levisingularity approved these changes

2024-03-15 15:38 UTC, merged