[das-query-engine#223] Updated kwargs documentation
singnet/das-query-engine pull request #271
Opened 2024-06-19 18:45 UTC by eddiebrissow

Added Kwargs documentation
closes #223

2024-06-19 19:57 UTC, andre-senna requested changes
Overall, the changes are OK but I missed a more "integrated" explanation of parameters. I mean, some of the parameters (specially kwargs) determine a behavior which is also tied to other parameters but your explanation is somehow independent for each parameter: first you explain parameter 1 and then you explain parameter 2 instead of providing an explanation which encompasses parameters 1 and 2.

2024-06-19 19:57 UTC, andre-senna commented on hyperon_das/das.py
> +            atomdb (str, optional): AtomDB type suported values are 'ram' and 'redis_mongo'. Defaults to 'ram'
The period is missing at the end of the paragraph. Please check all the following sentences because there are other ones with the same typo.

2024-06-19 19:57 UTC, andre-senna commented on hyperon_das/das.py
> +            mongo_hostname (str, optional): MongoDB hostname. Defailts to 'localhost'
Typo: Defailts --> Defaults. Please check a lot of occurrences of the same typo.

2024-06-19 19:57 UTC, andre-senna commented on hyperon_das/das.py
> +            redis_cluster (bool, optional): Indicates whether Redis is confiured in cluster mode. Defailts to True
Typo: confiured --> configured

2024-06-19 19:57 UTC, andre-senna commented on hyperon_das/das.py
> +            cursor (Any, optional): Start point to get the links.
It's impossible to understand what `cursor` does only by this explanation. I believe the behavior determined by `cursor` and `no_iterator == false` should be better explained.

2024-06-19 19:57 UTC, andre-senna commented on hyperon_das/das.py
> +            cursor (Any, optional): Start point to get the links.
Please fix other occurrences of these parameters in the API

2024-06-19 22:03 UTC, marcocapozzoli approved these changes

2024-06-24 18:49 UTC, andre-senna approved these changes

2024-06-25 17:07 UTC, merged